# Generated by Django 2.2.27 on 2023-11-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_task_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
