# Generated by Django 2.2.27 on 2023-11-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20231112_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='function_type',
            field=models.CharField(choices=[('1', 'Kalyanam'), ('2', 'Payat')], max_length=50, null=True),
        ),
    ]
