# Generated by Django 2.2.27 on 2023-11-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_task_function_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='function_type',
            field=models.CharField(choices=[('1', 'Kalyanam'), ('2', 'Payat')], default=1, max_length=50),
        ),
    ]
