# Generated by Django 2.2.27 on 2023-11-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20231112_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='function_type',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
