# Generated by Django 2.2.27 on 2023-11-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20231112_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='function_type',
        ),
    ]
