# Generated by Django 2.2.27 on 2023-11-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
